version: '3.8'
services:
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
        - "8443:8443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./ssl/:/etc/nginx/ssl/:ro
      restart: unless-stopped
      networks:
        - nginx-net

networks:
    nginx-net:
      driver: bridge
